version: '3'
# service
services:
    # mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    # proxy
    proxy:
        image: jwilder/nginx-proxy:latest
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
    # www
    www:
        image: atsu666/ioncube:7.2 # phpのバージョンにあったものを指定
        ports:
            - "8888:80"
        privileged: true
        volumes:
            - acms_data:/var/www/html
            # - ./html:/var/www/html
        links:
            - mysql:mysql
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html # ドキュメントルートを指定
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
            - MEMORY_LIMIT=128M
            - UPLOAD_LIMIT=64M
        ports:
            - 10099:80
volumes:
    acms_data: